### ISSUE TITLE
listRadio select does not work or needs better docs

### ISSUE THREAD

**Issue by bertvandepoel** [clue/php-zenity-react#38]
Based on the documentation I was trying to follow this structure for a radio button list dialog: 
```
$builder->listRadio(array $list, $text = null, array $selected = null);
```

However, I can't seem to get any radio button to be selected. First I tried lists (so with automatic keys) and an array of false, false, true so the last element would be selected. I also tried with 0 and 1 and with true and false as strings. Then I tried manual keys like:
```
$resolution = $launcher->waitFor($builder->listRadio(array('tb' => 'Overwrite the server, the record on my toughbook is correct', 'serv' => 'The record on the server is correct, overwrite the record on my toughbook', 'cancel' => 'I don\'t know, please cancel the synchronisation'), $conflicttext, array('tb' => 0, 'serv' => 0, 'cancel' => 1)));
```

Is this broken or am I missing something? The docs aren't very vocal about how this selected array is supposed to look to be fair.

**Comment by clue** [comment]
The `listRadio()` allows you to select a single entry from a list, as such it expects as single `$selected` entry. I'm not sure where you've seen this to be an array, but I agree that the documentation is a bit lacking in this regard.

In your case, you could pass `'tb'` as a value for `$selected` in order to select your first option.

See also the examples: https://github.com/clue/php-zenity-react/blob/9c25631e447cbc7bccc0ba09d3595db53389947e/examples/menu.php#L23

If you want to select multiple entries, you may want to use `listCheck()` instead. This one expects an array of keys in `$selected`.

In your case, you could pass `array('tb', 'serv')` as a value for `$selected` in order to select your first two options.

See also the examples: https://github.com/clue/php-zenity-react/blob/9c25631e447cbc7bccc0ba09d3595db53389947e/examples/menu.php#L27

**Comment by bertvandepoel** [comment]
I see, I only want to select the cancel option so that sounds perfect. README.md lists it as an array, that's what got me confused. I'll see if I have time later to write a PR to fix some of the docs.

**Comment by clue** [comment]
Indeed, thanks for spotting the README to be mixed up in this regard!

A PR would be much appreciated :+1:

**Comment by bertvandepoel** [comment]
Slightly later than expected (I'm doing this work at an excavation in Turkey, so you can probably imagine why) but I've sent you the pull request :wink:

**Comment by clue** [comment]
No worries, I'm happy you're alright and find the time to look into this, this is much appreciated :+1:
